services:
  postgresql:
    image: postgres:14
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: libuser
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U libuser -d library']
      interval: 2s
      timeout: 2s
      retries: 30
    volumes:
      - pg_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: 3000
      TYPEORM_SYNC: 'true'
      POSTGRESQL_HOST: postgresql
      POSTGRESQL_PORT: 5432
      POSTGRESQL_USER: libuser
      POSTGRESQL_PASSWORD: password
      POSTGRESQL_DATABASE: library
    ports:
      - '3000:3000'
    depends_on:
      postgresql:
        condition: service_healthy

volumes:
  pg_data: {}
